language: node_js
node_js: stable
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
- stty cols 80
dist: trusty
sudo: required
services:
- docker
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=avneetsingh/openebs-website;
    cd openebs_pro;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -f openebs_pro/Dockerfile -t $REPO:$COMMIT . && docker push $REPO; 
  fi
notifications:
  email:
    on_success: never
on_failure: always

