language: node_js
node_js: stable
env:
  global:
  - secure: gxKKYMa703ClVbFYA4IDjfUhRmHXl/gsekdG3THB0BOe39IeGHT3c+zJTipgpVPMJ8NXNdS35qJDdG3xDIIKgYfWYtpBdXLDofl3/iNmCIlLWEWu4oXmdcysjtD2sZ+0rsQfvX+EY4OIkuTW3Ob4Hdd5V6hCrBM/Gt90WCJkl2HFzSGL4KFiaWFX/ydXB4ql2M9dRmVDHaWknTEIxuoq6uikvWwuLE7i/i0BKVWOkcksbbMGx5TplbzWICbYJjL8UyhhVdq5a1OL2u5nfkptDH/AVEmIR3nKvPnzYTU2PievYNHJcOkpFeIsHATBvcSEG3F5ZkmjRYUQL/jfRANGXUrL6IGOoVulP7l1LLyiVt32FiFbS1tukYoTerqMoz84Jx+d7qly6CGSNzk7UmMO32nCdQG4m2n+MHMsUUnbP4Kcv+jS+X5QUunFlyQSCzWKVPw0D/0S8yVtfCvQEOElXluTQJeLidGfFg7N9My/jr/HnC6DUda4edMqeQu0Iy3tOm6vBF4QKFvgkbXLZg0I5LJzeleonfwIPpHP10bVyvkXEIibajmEmL/uYRoGSfPBA89QnbSQKKDRVBwKmZBTzQIIwJ/t4DPtDC9QTEw9G5yTAzU4BlMQu36ef0LWk9k0RphUln71WxLnPDJc0e1TOLMm2in5JucOX56m+R1QeBc=
  - secure: jPuuTUTqYnQTbxgAEP9DDzPXjc4FaE4bVwJt0rSlswXe2uIbx3eGFq8f5AJYA6CfvnY7Y+YDGyJ2p++Avy6lFcCnEQCV3gN+Vdr45ojQ23U04L95zOi44I5U/jnmMBFxgRZvK69IP7go3fSNt/DWKNRwXSGPA8AptO565ndVtPk6rniAlz8cQI0P5L+G5qOiu/ZY1LpkG17GGWtuUQARhl/s0qZFtLKo4kuA4fo3z4+kZ1UUapVMRwXLstO6F9Pna8BGvKPjMNBikHI/i8V6fedTdL6CN6LAM0ldqBXdPEV4lS5FVJbR6cJpu0VUlF4Z64u6l6GNm4L6nPBRlrEhCnMtn9A5yUYs2NoTttVSGwnhE92I6xuM3FG7kROajH8mTMULK3MZo0+M4rUpTabdrpCd9B1WFlUTEzTvJB7v23RIHNgUSbNXN3suIBdEd+RNTrMD86i5l3a5lZ3c8AKQpumVXsKs3ygWzEP0A0ew51L6JCXJeqnoMLemCO5sdEO5Z30gSI10Y1gvMNHPvVjRjsFYIhO30yUpVgQVjL5K303BqWX2L/V8OD0dIrHt1B8JE8PNF+lhs6yBJPZAFmPv3p2LEbzi9IvXrgfSURj5MTf79WAUyyOXMvZiIoiV+m3B/Y0AVmjXI3zI4Pp2h4Cj7iVdD8ReoubP5MZNrEBMPVs=
  - COMMIT=${TRAVIS_COMMIT::7}
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
after_success:
  - if  [ $TRAVIS_PULL_REQUEST = "false" ]; then export REPO=mayadata/www-openebs-io;
        docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -f openebs_pro/Dockerfile -t $REPO:$COMMIT . && docker push $REPO; 
    fi
notifications:
  #slack:
    #secure: n0Yi06sI+C6qmNqg3BAvV1GAubJ0pjAXZZNP6Tq5ZovpF5ES8GtAJSP6oHXJrfgPe85KGDpLR1NSLZAHdT9QISNYmbjbMYP4xM4ZpfNDbr8A6qXcbw5xVuIzzo9AENrXBANzTSAbfdEfqSzvwQibyqWzUQoHHZpNA8aTJ5OQCG8hHq00OprsumutxcR3MJC1EL4j2UDDBXU+1aaOo5PcxR1EAl8IcYShSCpzFbHDZnrsfkZvz3FEvZGCB7yJsGT0QrgEjSwDV38voDBNggICvyFbGGzupiu3jPfD4Dk50idvE9eTTFEF6e/pJMaMo1R+0FqPAqSTELNxeR2K4U2ba1Gk78BU1bJ6xw+0axjw1E21nlNabE3Eq5c/rvxNsxtRYMMroAX85UeBvupYZPbfq2tfV8PnGd15MaJZBkUmXqpVkiByg5of5/ntcajUq3JFlHX2aMU0oM1pJpm54RuOdK1hcTxo5i9AuP7d78FTRIWJH9G2qt3j1jy4rU24wo3d3/Mo2B9k3fUZ/2pqCvGewbxTcefebJJf1I9nngH3hhsPlbzkb7vUod3X7G0TysQOTlORyql3626Np5Rf4mJJ3jKUzBPO98uqL7Ygqow8c4gU2B1Hb2bWwwzYy9pMTuYMBhPMUAaY8pUyiu+DSfgfudYwGRh/nBpvifG/87isZ1k=
    email:
    recipients:
      - atulabhi.aa@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
