language: node_js
node_js: stable
env:
  global:
  - secure: q3CFBvPyfTS7XgZ6KOgYcREItw/FVnnwQW5nJZf6taA4YGjy363N934nT+p0ofRzQqlEykR/Qw90CVqMAmJAV7sBVypkB9hIutnP4lPyY+4moi5DIQwo7GWDC+mFJ1Pc5bDLdpcAW6vvKm8QKYw9N0nmZozIi8YKto2yxglElpH97BuSbvH7Q/8uD7X1xv87Yx6pBndM18B920wWAoDIgIhD0L/BPnlyIKDYdhip+VqpGHSph4LCAiHK5NDXhaBh7n4EmCyEcd7dq376v+Uj3NAECitu0rNwIPJ6Kno6o1mvSzsxhw2cKipbm3BcCtjfn/wGYAKXaSXow8HmtB08LRSu5Yb6/Fh6PsMySG9ZSPwZIi3rbwMwj22svLH16ntJ89N1P2ms/P6LIxq7WPg1P1P1dt9rpiBi7W5bEyqFz6nT9o9Is6uxu50rSB7+PDfI97HQtZqRq/QswqdkTs5fbJ4403Yib/oqP4hay+XjUfEB+BGZ4fUbieookaedGFrkXrs3Uwoef705iYVFxQdRWPLWBHAf3ScwVToFiiyJ4RAbq5qJu44zezHnb7sIBjJ1TyN3sU5FRlM0eQptBdhedxIz4CrgnpXMlEYAm4pSiKPHvQuVIgOLYziCWyHQgXgxouxK6JpPpf8fI0o75ukqIztc69r0oqjKcSLWuvvZnTA=
  - secure: ahrQbvjcoq9j6+GdERKxiNzhZP+6n6nsan85/jTZZL85YClcd9iqZLiPVE9hxmpBamYfjnlCXBHfVeqxe+TwdCI+5PWWRU4Qy/SaIIChncS/brhuIr/ZETZMy8x9/J44NWD6KBRfJeZkk3/hjefh8bZTWmBCfazauYS+MV9bYwsJdkmD4edaXbPUIshVnpJ3hC8ZBzI79Ez+8ZZVSafYWkvdO0izGFcV7CQ8L6IguxOmCpNAp1SEhy5wqyOC9ntb31x41umSM7Hx+CYmCJ1u0bv/66rS/olq0vJqZYthgIirmF7+uTKiDNroMGAwEjk4NC1eh/ee5SyoftbOkhAlQMh/07oAA3CMFU8SpyoBl21lue9hiaii1XkYcHPttRMoemqNcDJbpDBCOjgYhL3b+e29K23qsbjBPLyJG5rNzJsb7xYkYKODfqdHefHGp1XPedsvCjhgSoi3QdkaOkcyjhbJeOZD+1Co124RUmyCa3bp5hUJc6490VIESmcPyEl3gohgJazfDtm4tR+OUr/lk6oJ7W3oqNbcoC4sdK0X5xQ0mYvAAilSa7fSndw5iDgCXSLdwUnL4GRberAqL8+MfwDvV75OXvqtiaXYp11/l0EZ4OyrM1Et2hnnRmGfifCDVDtOfnTrzDzTDQk1gZGrR3BJ0q9tiZV8mapkjlcaXzE=
  - COMMIT=${TRAVIS_COMMIT::6}
before_install:
- stty cols 80
dist: trusty
sudo: required
services:
- docker
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
after_success:
- if  [ [$TRAVIS_PULL_REQUEST = "false" && $TRAVIS_BRANCH == "master" ]]; then export REPO=avneetsingh/openebs-website;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -f openebs_pro/Dockerfile -t $REPO:$COMMIT . && docker push $REPO; 
  fi
notifications:
  email:
    on_success: never
on_failure: always

